[tool.black]
line-length = 99
include = '\.pyi?$'
exclude = '''
/(
    \.eggs
  | \.git
  | \.mypy_cache
  | \.tox
  | \.venv
  | build
  | dist
  | tests/assets
)/
'''

[tool.ruff]
line-length = 99
select = [
  "E",  # Pyflakes
  "F",  # Pycodestyle
  "I",  # isort
]
src = ["reprexlite", "tests"]
exclude = ["tests/assets"]

[tool.ruff.isort]
known-first-party = ["reprexlite"]
known-third-party = ["IPython"]
force-sort-within-sections = true

[tool.mypy]
ignore_missing_imports = true

[tool.pytest.ini_options]
minversion = "6.0"
addopts = "--cov=reprexlite --cov-report=term --cov-report=html --cov-report=xml"
testpaths = ["tests"]

[tool.coverage.run]
source = ["reprexlite"]
