[tool.black]
line-length = 99
target-version = ['py36', 'py37', 'py38']
include = '\.pyi?$'
exclude = '''
/(
    \.eggs
  | \.git
  | \.mypy_cache
  | \.tox
  | \.venv
  | build
  | dist
  | tests/assets
)/
'''

[tool.isort]
profile = "black"
multi_line_output = 3
force_sort_within_sections = true
