site_name: reprexlite
site_url: https://jayqi.github.io/reprexlite
site_description: Render reproducible examples of Python code for sharing.
repo_url: https://github.com/jayqi/reprexlite

nav:
  - Home: "index.md"
  - Design Philosophy: "design-philosophy.md"
  - Reprex Do's and Don'ts: "dos-and-donts.md"
  - Usage:
      - Basic Usage: "./#basic-usage"
      - CLI Help: "cli.md"
      - Rendering and Output Venues: "rendering-and-output-venues.md"
      - Configuration: "configuration.md"
      - IPython/Jupyter Magic: "ipython-jupyter-magic.ipynb"
  - Library:
      - API Reference:
          - reprexlite.config: "api-reference/config.md"
          - reprexlite.exceptions: "api-reference/exceptions.md"
          - reprexlite.formatting: "api-reference/formatting.md"
          - reprexlite.parsing: "api-reference/parsing.md"
          - reprexlite.reprexes: "api-reference/reprexes.md"
          - reprexlite.session_info: "api-reference/session_info.md"
  - Changelog: "changelog.md"
  - Alternatives: "alternatives.md"

theme:
  name: material
  features:
    - navigation.sections # top-level groups are section headers
    - navigation.top # adds back-to-top button
  logo: images/reprexlite.svg
  favicon: images/reprexlite_white_blue.svg
  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      primary: indigo
      accent: blue
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      primary: indigo
      accent: blue
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      primary: indigo
      accent: blue
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to system preference
  custom_dir: overrides/

extra_css:
  - css/extra.css

markdown_extensions:
  - attr_list:
  - github-callouts:
  - mdx_truly_sane_lists:
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
  - pymdownx.superfences:
  - tables:
  - toc:
      permalink: true
      toc_depth: 3

plugins:
  - search:
  - macros:
  - mkdocs-jupyter:
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          paths: [../reprexlite]
          options:
            # General
            docstring_style: google
            # Headings options
            heading_level: 2
            show_root_toc_entry: false
            show_root_full_path: false
            show_root_heading: false
            show_category_heading: true
            # Members options
            filters: ["!^_", "^__init__$"]
            # Docstrings options
            show_if_no_docstring: false
            merge_init_into_class: true
            # Signatures/annotation options
            annotations_path: brief
            separate_signature: true
            show_signature_annotations: true
            unwrap_annotated: true
            # Additional options
            show_source: true
  - mike:
      alias_type: copy
      canonical_version: stable
      version_selector: true

extra:
  version:
    provider: mike
    default: stable
    alias: true
