site_name: reprexlite
site_url: https://jayqi.github.io/reprexlite
site_description: Render reproducible examples of Python code for sharing.
repo_url: https://github.com/jayqi/reprexlite
theme:
  name: material
  logo: images/reprexlite.svg
  favicon: images/reprexlite_white_blue.svg

nav:
  - Home: "index.md"
  - Design Philosophy: "design-philosophy.md"
  - Reprex Do's and Don'ts: "dos-and-donts.md"
  - CLI Help: "cli.md"
  - API Reference:
      - reprexlite: "api-reference/reprex.md"
      - reprexlite.code: "api-reference/code.md"
      - reprexlite.formatting: "api-reference/formatting.md"
      - reprexlite.session_info: "api-reference/session_info.md"
  - Changelog: "changelog.md"

extra_css:
  - stylesheets/custom_mkdocstrings.css

markdown_extensions:
  - pymdownx.highlight:
  - pymdownx.superfences:
  - toc:
      permalink: true
      toc_depth: 3
  - mdx_truly_sane_lists:

plugins:
  - search
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          selection:
            filters: ["!^_(?!_init__)"]
            inherited_members: true
          rendering:
            show_root_heading: false
            show_root_toc_entry: false
            show_root_full_path: false
            show_if_no_docstring: true
            show_signature_annotations: false
            show_source: true
            heading_level: 2
            group_by_category: true
            show_category_heading: true
