site_name: reprexlite
site_url: https://jayqi.github.io/reprexlite
site_description: Render reproducible examples of Python code for sharing.
repo_url: https://github.com/jayqi/reprexlite
theme:
  name: material
  logo: images/reprexlite.svg
  favicon: images/reprexlite_white_blue.svg
  features:
    - navigation.top

nav:
  - Home: "index.md"
  - Design Philosophy: "design-philosophy.md"
  - Reprex Do's and Don'ts: "dos-and-donts.md"
  - CLI Help: "cli.md"
  - IPython/Jupyter Magic: "ipython-jupyter-magic.ipynb"
  - Alternatives: "alternatives.md"
  - API Reference:
      - reprexlite: "api-reference/reprex.md"
      - reprexlite.config: "api-reference/config.md"
      - reprexlite.exceptions: "api-reference/exceptions.md"
      - reprexlite.formatting: "api-reference/formatting.md"
      - reprexlite.parsing: "api-reference/parsing.md"
      - reprexlite.reprexes: "api-reference/reprexes.md"
      - reprexlite.session_info: "api-reference/session_info.md"
  - Changelog: "changelog.md"

extra_css:
  - css/custom_mkdocstrings.css

markdown_extensions:
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight:
  - pymdownx.superfences:
  - toc:
      permalink: true
      toc_depth: 3
  - mdx_truly_sane_lists:

plugins:
  - search:
  - mkdocs-jupyter:
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          paths: [../reprexlite]
          options:
            # Headings options
            heading_level: 2
            show_root_toc_entry: false
            show_root_full_path: false
            show_root_heading: false
            show_category_heading: true
            # Members options
            filters: ["!^_(?!_init__)"]
            group_by_category: true
            inherited_members: true
            # Docstrings options
            show_if_no_docstring: false
            # Signatures/annotation options
            show_signature_annotations: true
            # Additional options
            show_source: true

extra:
  version:
    provider: mike
