name: docs-preview

on:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    name: Build docs and deploy preview
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: extractions/setup-just@v2

      - uses: astral-sh/setup-uv@v5

      - name: Build docs
        run: |
          just docs

      - name: Get git commit short hash
        id: commit_hash
        run: |
          GIT_SHORT_HASH=$(git rev-parse --short HEAD)
          echo "GIT_SHORT_HASH=$GIT_SHORT_HASH" >> $GITHUB_OUTPUT

      - name: Deploy docs preview to Netlify
        if: |
          github.event.pull_request != null
        uses: nwtgck/actions-netlify@v2.0.0
        with:
          publish-dir: "./docs/site"
          production-deploy: false
          github-token: ${{ secrets.GITHUB_TOKEN }}
          deploy-message: "Deploy from GitHub Actions"
          enable-pull-request-comment: true
          enable-commit-comment: false
          overwrites-pull-request-comment: true
          alias: deploy-preview-${{ steps.commit_hash.outputs.GIT_SHORT_HASH }}
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        timeout-minutes: 1
