name: release
run-name: Release of ${{ inputs.version }}

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version tag'
        required: true

jobs:
  build:
    name: Publish new release
    runs-on: "ubuntu-latest"

    steps:
      - uses: actions/checkout@v4

      - uses: astral-sh/setup-uv@v5

      - name: Check that versions match
        run: |
          echo "Input version tag: [${{ github.event.inputs.version }}] "
          PACKAGE_VERSION=$(uv run python -m vspect read .)
          echo "Package version: [$PACKAGE_VERSION]"
          [[ ${{ github.event.inputs.version }} == "v$PACKAGE_VERSION" ]] || { exit 1; }

      - name: Build package
        run: |
          uv build

      - name: Publish to Test PyPI
        uses: pypa/gh-action-pypi-publish@v1.3.0
        with:
          user: __token__
          password: ${{ secrets.PYPI_TEST_TOKEN }}
          repository_url: https://test.pypi.org/legacy/
          skip_existing: true

      - name: Publish to Production PyPI
        uses: pypa/gh-action-pypi-publish@v1.3.0
        with:
          user: __token__
          password: ${{ secrets.PYPI_PROD_TOKEN }}
          skip_existing: false

      - id: extract-changelog
        uses: sean0x42/markdown-extract@v2.1.0
        with:
          file: CHANGELOG.md
          pattern: ${{ github.event.inputs.version }}

      - name: Write output to file
        run: |
          cat <<'__EOF__' > __CHANGELOG-extracted.md
          ${{ steps.extract-changelog.outputs.markdown }}
          __EOF__

      - uses: ncipollo/release-action@v1
        with:
          tag: ${{ github.event.inputs.version }}
          commit: main
          artifacts: "dist/*.whl,dist/*.tar.gz"
          bodyFile: "__CHANGELOG-extracted.md"
